# Generated by Django 5.0.2 on 2024-04-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_task_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(max_length=100),
        ),
    ]
