# Generated by Django 4.2.10 on 2024-04-23 03:06

import accounts_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must start with 3 uppercase letters denoting company followed by 3 digits.', regex='^[A-Z]{3}\\d{3}$')])),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128, null=True, validators=[accounts_app.models.CustomUser.password_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('allowNotifications', models.BooleanField(default=False)),
                ('notifyThrough', models.CharField(default='Messages', max_length=9)),
                ('notifyforTasks', models.BooleanField(default=False)),
                ('notifyforEvents', models.BooleanField(default=False)),
                ('notifyforMessages', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
